package com.nevzatcirak.assistant.core.usecase;

import com.nevzatcirak.assistant.api.model.*;
import com.nevzatcirak.assistant.api.port.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

/**
 * Core business logic for handling chat interactions.
 * <p>
 * This class implements the RAG (Retrieval Augmented Generation) pattern by:
 * 1. Retrieving relevant context from the Vector Store.
 * 2. Constructing a system prompt with the persona and context.
 * 3. Delegating the generation to the LLM Port.
 * </p>
 */
public class ChatUseCase {

    private static final Logger logger = LoggerFactory.getLogger(ChatUseCase.class);

    private final LlmPort llmPort;
    private final VectorStorePort vectorStorePort;
    private final PersonProfile personProfile;

    /**
     * Constructs a new ChatUseCase.
     *
     * @param llmPort         Port for Large Language Model interactions.
     * @param vectorStorePort Port for Vector Database operations.
     * @param personProfile   Configuration for the assistant's persona.
     */
    public ChatUseCase(LlmPort llmPort, VectorStorePort vectorStorePort, PersonProfile personProfile) {
        this.llmPort = llmPort;
        this.vectorStorePort = vectorStorePort;
        this.personProfile = personProfile;
    }

    /**
     * Processes a user query and returns an AI-generated response.
     *
     * @param conversationId The unique ID of the conversation session (for memory).
     * @param query          The user's input query.
     * @return The response generated by the AI assistant.
     */
    public AssistantResponse chat(String conversationId, UserQuery query) {
        logger.info("Processing chat request for conversationId: {}", conversationId);
        logger.debug("User Query: {}", query.text());

        List<String> similarDocs = vectorStorePort.findSimilar(query.text(), 3);
        String context = similarDocs.isEmpty() ? "No specific context available." : String.join("\n---\n", similarDocs);

        logger.debug("Retrieved {} relevant document segments from Vector Store.", similarDocs.size());

        String systemPrompt = String.format("""
            You are the AI Assistant for %s %s, who is a %s.

            INSTRUCTIONS:
            - Answer questions based on the CONTEXT provided below and the Conversation History.
            - If the answer is not in the context, say "I don't have information about that."
            - Be professional and helpful.

            CONTEXT:
            %s
            """,
            personProfile.firstName(),
            personProfile.lastName(),
            personProfile.role(),
            context
        );

        return llmPort.generate(conversationId, systemPrompt, query);
    }
}